/*
 *  Raptor: Call of the Shadows clone
 *  Copyright (C) 2020 A. Roldán
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * 	arldn.dev -at- gmail.com
 */

#ifndef __definitions_h
#define __definitions_h

#define FILENAME_DATA   "DATA.RES"
#define FILENAME_INI    "RAPTOR.INI"
#define FILENAME_ICON   "ICON.BMP"
//#define DATA_PATH       "DATA/"
#define DATA_PATH       "../resources/dist/"

#define VIDEO_SCREEN_WIDTH      320
#define VIDEO_SCREEN_HEIGHT     200
#define VIDEO_SCREEN_FPS        60
#define VIDEO_SCREEN_TITLE      "Raptor: Call of the Shadows"

#define PROPELLER_HEIGHT    10

#define PILOT_ACCELERATION          0.3f
#define PILOT_DECELERATION          0.4f
#define PILOT_MAX_X_ACCELERATION    4.0f
#define PILOT_MAX_Y_ACCELERATION    3.5f

#define GAME_SCENE_SPEED		0.37f

#define TILE_SIZE	32
//#define GAME_ENEMY_APPEAR_ROWS	3

enum {
    IMAGE_TILESET_A = 0,
    IMAGE_PILOT_LEFT_2 = 1,
    IMAGE_PILOT_LEFT_1 = 2,
    IMAGE_PILOT_IDLE = 3,
    IMAGE_PILOT_RIGHT_1 = 4,
    IMAGE_PILOT_RIGHT_2 = 5,
    IMAGE_FONT_CREDITS = 6,
    IMAGE_BOMB = 7,
    IMAGE_SHIELD = 8,

    IMAGE_BULLET_MACHINEGUN_1 = 9,
    IMAGE_BULLET_MACHINEGUN_2 = 10,
    IMAGE_BULLET_MACHINEGUN_3 = 11,
    IMAGE_BULLET_MACHINEGUN_4 = 12,

    IMAGE_EXPLOSION_FLARE_START = 13,
    IMAGE_EXPLOSION_BUILDING_START = 39,
    IMAGE_SPARKLE_START = 74,

    IMAGE_ENEMY_1 = 91,

    IMAGE_BSPARK_START = 96,
    IMAGE_OSPARK_START = 105,

    IMAGE_HANGAR_START = 114,

    IMAGE_CURSOR = 116,

    IMAGE_HANGAR_TEXT_START = 117,
    IMAGE_HANGAR_TEXT_SUPPLY = IMAGE_HANGAR_TEXT_START,
    IMAGE_HANGAR_TEXT_FLY = 118,
    IMAGE_HANGAR_TEXT_SAVE = 119,
    IMAGE_HANGAR_TEXT_EXIT = 120,

    IMAGE_FLY_TEXT_BRAVO = 121,
    IMAGE_FLY_TEXT_TANGO = 123,
    IMAGE_FLY_TEXT_OUTER = 125,
    IMAGE_FLY_TEXT_AUTO = 127,

    IMAGE_FLY_BACKGROUND = 129,
    IMAGE_STORE_BACKGROUND = 130,

    IMAGE_STORE_ACTIONS = 131,
    IMAGE_STORE_COST = 132,
    IMAGE_STORE_HAVE = 133,
    IMAGE_STORE_RESALE = 134,
    IMAGE_STORE_SELECT = 135,

    IMAGE_STORE_FONT = 136,

    IMAGE_STORE_ITEMS = 137,

    IMAGE_MENU_BACKGROUND = 138,
    IMAGE_NEWPILOT_BACKGROUND = 139,

    IMAGE_PICTURE_PILOT_START = 140,
    IMAGE_PICTURE_PILOT_END = 143,

    IMAGE_MIN_PILOT_START = 144,
    IMAGE_MIN_PILOT_END = 147,

    IMAGE_BONUS = 148,

    IMAGE_SHOT_MISSILEAIR_START = 149,
    IMAGE_SHOT_MISSILEAIR_SIZE = 2,
    IMAGE_SHOT_MISSILEAIR_END = 150,

    IMAGE_SHOT_ENEMY_1 = 151,
    IMAGE_SHOT_ENEMY_2 = 152,

    IMAGE_EXPLOSION_SHIP_START = 153,
    IMAGE_EXPLOSION_SHIP_SIZE = 16,
    IMAGE_EXPLOSION_SHIP_END = IMAGE_EXPLOSION_SHIP_START + IMAGE_EXPLOSION_SHIP_SIZE,

    IMAGE_EXPLOSION_HIT_START = 169,
    IMAGE_EXPLOSION_HIT_SIZE = 14,
    IMAGE_EXPLOSION_HIT_END = IMAGE_EXPLOSION_HIT_START + IMAGE_EXPLOSION_HIT_SIZE,

    IMAGE_ENEMY_HELICOPTER1_START = 183,
    IMAGE_ENEMY_HELICOPTER1_SIZE = 4,
    IMAGE_ENEMY_HELICOPTER1_END = IMAGE_ENEMY_HELICOPTER1_START + IMAGE_ENEMY_HELICOPTER1_SIZE,

    IMAGE_SHOT_ENEMY_MISSILE_1 = 187,
    IMAGE_SHOT_ENEMY_MISSILE_2 = 188,

	IMAGE_MENU_LABELS = 189,
	IMAGE_MENU_LABELS_SELECTED = 190,
	IMAGE_LOGO = 191,

	IMAGE_OPTION_SELECT = 192,
	IMAGE_OPTION_SLIDE = 193,
	IMAGE_DIALOG_BUTTON = 194,
	IMAGE_DIALOG_BACKGROUND = 195,

	IMAGE_MEGABOMB_BULLET_START = 196,
	IMAGE_MEGABOMB_BULLET_SIZE = 4,
	IMAGE_MEGABOMB_BULLET_END = IMAGE_MEGABOMB_BULLET_START + IMAGE_MEGABOMB_BULLET_SIZE,

	IMAGE_ENEMY_BONUS1 = 200,

	IMAGE_EXPLOSION_START = 201,
	IMAGE_EXPLOSION_SIZE = 13,
	IMAGE_EXPLOSION_END = IMAGE_EXPLOSION_START + IMAGE_EXPLOSION_SIZE,

	IMAGE_BONUS_EXPLOSION_START = 214,
	IMAGE_BONUS_EXPLOSION_SIZE = 12,
	IMAGE_BONUS_EXPLOSION_END = IMAGE_BONUS_EXPLOSION_START + IMAGE_BONUS_EXPLOSION_SIZE,

	IMAGE_EXPLOSION_EXTRALARGE_START = 226,
	IMAGE_EXPLOSION_EXTRALARGE_SIZE = 12,
	IMAGE_EXPLOSION_EXTRALARGE_END = IMAGE_EXPLOSION_EXTRALARGE_START + IMAGE_EXPLOSION_EXTRALARGE_SIZE,

	IMAGE_GLOW_ITEM_START = 238,
	IMAGE_GLOW_ITEM_SIZE = 4,
	IMAGE_GLOW_ITEM_END = IMAGE_GLOW_ITEM_START + IMAGE_GLOW_ITEM_SIZE,

	IMAGE_BUILDING_BONUS_1 = 242,

	IMAGE_ENEMY_4 = 243,
	IMAGE_ENEMY_5 = 244,

	IMAGE_ENEMY_SHIP1_1 = 245,
	IMAGE_ENEMY_SHIP1_2 = 246,

	IMAGE_ENEMY_6 = 247,
	IMAGE_ENEMY_7 = 248,

    IMAGE_ENEMY_SHIP2_1 = 249,
    IMAGE_ENEMY_SHIP2_2 = 250,

    IMAGE_ENEMY_BALL_1 = 251,
    IMAGE_ENEMY_BALL_2 = 252,

    IMAGE_BOSS_1 = 253,

    IMAGE_PROPELLER_START = 254,
    IMAGE_PROPELLER_SIZE = 5,
    IMAGE_PROPELLER_END = IMAGE_PROPELLER_START + IMAGE_PROPELLER_SIZE

    // 259
};

enum {
    SOUND_MACHINEGUN = 0,
    SOUND_PAUSE = 1,
    SOUND_EXPLOSION_BUILDING = 2,
    SOUND_STORE = 3,
    SOUND_HANGAR = 4,
    SOUND_MISSILE_1 = 5,
    SOUND_MISSILE_2 = 6,
    SOUND_EXPLOSION_SHIP = 7,
    SOUND_SHOT_ENEMY = 8,
    SOUND_HIT = 9,
    SOUND_BONUS = 10
};

enum {
    MUSIC_APOGEE = 0,
    MUSIC_HANGAR = 1,
    MUSIC_SECTOR_BRAVO_1 = 2,
    MUSIC_MENU = 3
};

enum {
    FONT_DEFAULT = 0
};

enum {
    DIFFICULTY_TRAINING = 0,
    DIFFICULTY_ROOKIE = 1,
    DIFFICULTY_VETERAN = 2,
    DIFFICULTY_ELITE = 3
};

enum {
    WEAPON_MACHINEGUN = 0,
    WEAPON_ENEMY = 1,
    WEAPON_AIRAIR_MISSILE = 2,
    WEAPON_ENEMY_MISSILE = 3,
    WEAPON_ENEMY_TARGET = 4
};

typedef enum _GAMESTATE {
	GAMESTATE_NONE,
    GAMESTATE_MAINMENU,
    GAMESTATE_HANGAR,
    GAMESTATE_STORE,
    GAMESTATE_DEAPERTURE,
    GAMESTATE_ARRIVAL,
    GAMESTATE_GAME,
    GAMESTATE_NEWGAME,
	GAMESTATE_GAMEOVER
} GAMESTATE;

enum {
    SHIP_PILOT,
    SHIP_ENEMY_1,
    SHIP_ENEMY_2,
    SHIP_BONUS_1,
    SHIP_BUILDING_BONUS_1,
    SHIP_ENEMY_4,
    SHIP_ENEMY_5,
    SHIP_SHIP_1,
    SHIP_ENEMY_6,
    SHIP_ENEMY_7,
    SHIP_SHIP_2,
    SHIP_BALL,
    SHIP_BOSS_1,

    SHIP_LAST
};

// Milliseconds to spread explosion among buildings
#define GAME_EXPLOSION_SPREAD_DELAY  800

// Max side spreading
#define GAME_MAX_SPREADING      3

// Milliseconds to regenerate 1 point of energy
#define GAME_REGENERATION_DELAY      4500

#define GAME_DAMAGE_COLLISION		10

#define GAME_COLLISION_DELAY		50

#define CONSOLE_FEEDBACK_TIME		2500

#define GAME_MEGABOMB_TARGET_W      16
#define GAME_MEGABOMB_TARGET_H      16
#define GAME_MEGABOMB_TARGET_X      VIDEO_SCREEN_WIDTH / 2 - GAME_MEGABOMB_TARGET_W / 2
#define GAME_MEGABOMB_TARGET_Y      VIDEO_SCREEN_HEIGHT / 3 - GAME_MEGABOMB_TARGET_H / 2
#define GAME_MEGABOMB_VELOCITY      1.0f
#define GAME_MEGABOMB_DAMAGE        100
#define GAME_MEGABOMB_BULLET_SIZE   8

#define GAME_BURSTINGUP_TIME		3000
#define GAME_BOSS_DEFAT_DELAY		4000
#define GAME_GAMEOVER_EXPLOSIONS	8
#define GAME_GAMEOVER_DELAY			1000

#define GAME_MAX_GANG               4

#define CHANCE(a) (rand() % a)

enum {
    ITEM_ENERGYMODULE       = 0,    // 0x10
    ITEM_MACHINEGUN         = 1,    //
    ITEM_IONSCANNER         = 2,    //
    ITEM_MEGABOMB           = 3,    // 0x0b
    ITEM_AIRAIRMISSILE      = 4,    // 0x07
    ITEM_PHASESHIELD        = 5,    // 0x0f
    ITEM_PLASMACANNON       = 6,    // 0x01
    ITEM_AIRGROUNDMISSILE   = 7,    // 0x08
    ITEM_DUMBFIREMISSILE    = 8,    // 0x03
    ITEM_MICROMISSILE       = 9,    // 0x02
    ITEM_MISSILEPOD         = 10,   // 0x06
    ITEM_AUTOTRACK          = 11,   // 0x04
    ITEM_PULSECANNON        = 12,   // 0x0c
    ITEM_ENEMYBASICWEAPON   = 13,   //
    ITEM_BONUS              = 14,    // 0x17,

    ITEM_LAST
};

#endif  /* __definitions_h */